name: Automate Versioning and Changelog 

on: 
  push: 

jobs:
  versioning:
    name: Automate Versioning and Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |  
          git config --global user.name "pkumard4"          
          git config --global user.email "pradee030@gmail.com"

      - name: Push Initial Tag
        env:
          PAT: ${{ secrets.CHANGELOG_TOKEN }}
        run: |
          git tag 1.0.0
          git push https://x-access-token:${PAT}@github.com/devops26012024/Playback_Terrafrom.git 1.0.0
          
      - name: Generate Changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_TOKEN }}
        run: |
          npx conventional-changelog-cli -p angular -i CHANGELOG.md -s
          git add CHANGELOG.md
          git commit -m "chore: update changelog"

      - name: Increment Version
        id: version
        run: |
          current_version=$(git tag | tail -n 1)
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF += 1; print}')
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create and Push New Version Tag
        env:
          PAT: ${{ secrets.CHANGELOG_TOKEN }}
        run: |
          git tag ${{ env.new_version }}
          git push https://x-access-token:${PAT}@github.com/devops26012024/Playback_Terrafrom.git ${{ env.new_version }}
